### PR TITLE
Filter only certain occurrences

### PR DESCRIPTION
**Pull request by alexancp**
Thanks for this package.

I sometimes have identical prints, but I might want to test them to different thresholds. 
Therefore, I added a new keyword, `check_occurences`, to the `filter_constructor.py` and tried to modify `scissors.py` to skip other occurrences. 
If I'm interested in the first and second time a number is printed I would set the filter option to `check_occurences=[1,2]`
and all other occurrences of the string are not filtered.

### CODE REVIEW

**Comment by miroi** [comment]
I am in  favor of this change. 

Is this change meant to work with DIRAC first  ? Also, I would welcome this new functionality test in https://github.com/bast/runtest/tree/main/runtest/test .

**Comment by alexancp** [comment]
I added a test to the test folder now. I'm not sure what you mean by the first question. I'm not working on DIRAC but eT, if you were meaning that.

**Comment by miroi** [comment]
Thanks. I was thinking on DIRAC as repeating data occurs in DIRAC outputs as well, so your runtest extension shall fit for this software as well.

**Comment by miroi** [comment]
Rado ( @bast ), I see no automatic tests before the merge request....is this wanted for runtest ?

**Comment by alexancp** [comment]
> Thanks. I was thinking on DIRAC as repeating data occurs in DIRAC outputs as well, so your runtest extension shall fit for this software as well.

I'm glad if it can also be used in other programs :relaxed:

**Comment by alexancp** [comment]
> Rado ( @bast ), I see no automatic tests before the merge request....is this wanted for runtest ?

It seems like the pipeline needs to be approved by a maintainer.

**Comment by bast** [comment]
Thanks a lot for this change! I will review soon and comment or merge. About the tests: strange that I don't even see a question whether to approve the CI run. I need to look into that. This is not expected.

**Comment by bast** [comment]
Can I ask: why would the tolerance be different from line to line? Is this something that is not deterministic and not even with a random seed?

**Comment by miroi** [comment]
> Can I ask: why would the tolerance be different from line to line? Is this something that is not deterministic and not even with a random seed?

This could be fine for checking different lines, for example, printing same quantities in various output places with different accuracy/level of convergence.

**Comment by bast** [comment]
Ah I see. I get it now.

**Comment by alexancp** [comment]
I would like to use it when we use two solvers to solve e.g. for excited states. The first one would only converge the roots to a lower threshold while the second solver is used for tighter convergence. Both solvers would print a summary of the excitation energies, but I cannot use the same threshold to check them.

**Comment by bast** [comment]
Sorry for asking still (this does not mean that this PR is a bad idea, only to sharpen it so that we all understand it 100% since once something is added it is there "forever"):

Could the above be solved by printing "Result from solver X" followed by a generic output that is similar? I mean there is somewhere close to the output printed for humans what this output refers to. And could the testing use that instead? Could we solve it by better support for regular expressions? (see also #23)

**Comment by alexancp** [comment]
That is a fair question to ask. 
I would say that the idea of this PR is similar to the idea of `mask`, as it allows to selectively ignore certain parts of the output.
This problem could definitely be solved by changing the print in the output, but this is probably true for any problem.

I think this can't be easily solved with regex because `scissors.py` only considers a single line at a time.

I agree that the solution with counting occurrences is not very pretty and I realized that I can solve the issue I have using the `from_string`, `to_string` keywords.

**Comment by bast** [comment]
Maybe the occurrence counting is the right way.

Good point about the line-by-line problem. But this is something that we could change. It seems an internal choice. Assuming that the `scissors.py` would not go line by line but actually extract text portions based on regexes, would this solve the problem without renaming anything in the output which I understand is not always possible or desirable.

**Comment by miroi** [comment]
Ad: "Maybe the occurrence counting is the right way." 

Folks, we have the geometry optimization mathod, in each iteration is provided with identical strings ("Optimization ifnormation"), see for example https://gitlab.com/dirac/dirac/-/blob/master/test/dft_geo_opt/result/lda_numgra_h2.out?expanded=true&viewer=simple#L39488 .  Therefore it is good to check only certain occurences of the geometry optimization strings.  In general, in various iteration processes it is good to have tool for checking selected string occurences.

**Comment by bast** [comment]
But why not checking all of the iterations?

**Comment by miroi** [comment]
> But why not checking all of the iterations?

Good point. I would check the first iteration  - to control the setting of initial params (hessian etc), and the last (has it converged within limits ?), and the rest in between first and last may be affected with numerical issues. The same with SCF iterations - checking first (are starting densities well ?) and last. Also RelCC iterations - first and last, if printed.

**Comment by bast** [comment]
But they are deterministic and you would like to notice if it suddenly takes 30 iterations instead of 6. You might miss that if you only check first and last.

**Comment by miroi** [comment]
> are deterministic and you would like to notice if it suddenly takes 30 iterations instead of 6

For numerically stable cases it could be 30 iteration on all platforms/with all possible math libraries. But it could be also 29, or 32. This proposed change extends the filtering for such cases.

**Comment by bast** [comment]
I would consider such behavior a bug though :-)

But I see your point. I will think just a little bit more about it whether we can solve this with regexes. But maybe regexes are also too hard/"unfriendly" as input format.

**Comment by bast** [comment]
And how would you ask for the last?

**Comment by bast** [comment]
But just to be clear: I really appreciate this PR and will process it now soon. I have just been very busy last week. With my questions I only want to sharpen the API.

**Comment by miroi** [comment]
> And how would you ask for the last?

Good point. We do not know its number beforehand. I would use some Python trick - iterate via a cycle untill we got proper reading of last string occurence, and extract its number...Either 30, or 31, or 29...

**Comment by miroi** [comment]
> I would consider such behavior a bug though :-)

When thinking about various iteration methods in numerical mathematics (and quantum chemistry), there are many cases where number of iterations for the same case differ based on numerical stability, platform, math libraries. 6 iters vs 30 could be a bug, but 29 vs 30 is fine.

**Comment by bast** [comment]
To get the last element: perhaps we could use -1. But for this it would be good if we started counting from 0. Maybe also for the mask but that could break existing tests. But maybe we could find a better word for "mask" anyway and leave it as deprecated and rename it.

**Comment by bast** [comment]
Sorry I forgot this one ... reviving it.

**Comment by bast** [comment]
Now we are almost a year later and I am wondering. Is this functionality still wanted? If yes, then I can fix conflicts and think more about a consistent API.

So how do you see it now a year later?

**Comment by alexancp** [comment]
I don't need it anymore and I see that there are certainly more elegant solutions for this problem. It's fine for me to close this PR.

**Comment by bast** [comment]
Thanks. Sorry this never materialized. I really appreciate the work. Thanks for using this and thanks for your contributions.

**Pull request closed without merging**
